export const toolOptions = [
    { value: 'JavaScript', label: 'JavaScript' },
    { value: 'Ruby', label: 'Ruby' },
    { value: 'C', label: 'C' },
    { value: 'Shell', label: 'Shell' },
    { value: 'TypeScript', label: 'TypeScript' },
    { value: 'C++', label: 'C++' },
    { value: 'C#', label: 'C#' },
    { value: 'PHP', label: 'PHP' },
    { value: 'Java', label: 'Java' },
    { value: 'Python', label: 'Python' },
    { value: 'Unity', label: 'Unity' },
    { value: 'Microsoft Word', label: 'Microsoft Word' },
    { value: 'Microsoft Excel', label: 'Microsoft Excel' },
    { value: 'Microsoft PowerPoint', label: 'Microsoft PowerPoint' },
    { value: 'Microsoft Word', label: 'Microsoft Word' },
    { value: 'Skype', label: 'Skype' },
    { value: 'Adobe Photoshop', label: 'Adobe Photoshop' },
    { value: 'Adobe Illustrator', label: 'Adobe Illustrator' },
    { value: 'Other', label: 'Other' },
  ]

